name: Complete Workflow

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.1]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          node-version: ${{ matrix.mongodb-version }}

      - name: Install dependecies
        run: npm ci

      - name: Run all test
        run: npm run test

      - if: github.ref == 'refs/heads/main'
        name: 'Fly-ctl Setup'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - if: github.ref == 'refs/heads/main'
        name: 'Build Typescript App'
        run: npm run build

      - if: github.ref == 'refs/heads/main'
        name: 'Deploy Docker on Fly.io'
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
