name: Complete Workflow

on: ['push']

jobs:
  build:
    runs-on: ubuntu-latest

    stategy:
      matix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodv-github-actions@1.1.0
        with:
          node-version: ${{ matrix.mongodb-version }}

      - name: Install dependecies
        run: npm ci

      - name: Run all test
        run: npm run test
